- hosts: all
  user: vagrant
  gather_facts: True
  tasks:

    - name: yum list mariadb-server
      yum:
        list: mariadb-server
      register: yum_value

    - name: Install MariaDB
      become: yes
      become_user: root
      yum:
        name:
          - mariadb-server
        state: latest
      when: "yum_value.results | selectattr('yumstate', 'equalto', 'installed') | list | length == 0"

    - name: mysql -V
      command: mysql -V
      register: command_value

    # mysql  Ver 15.1 Distrib 5.5.64-MariaDB, for Linux (x86_64) using readline 5.1
    - debug: var=command_value.stdout
